name: Deploy Node + React App (Self-Hosted Windows)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]

    steps:
      # --- CHECKOUT ---
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- NODE SETUP ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # --- CLIENT (React App) ---
      - name: Ensure Client Lockfile & Install Dependencies
        shell: powershell
        run: |
          if (-Not (Test-Path "client")) {
            Write-Host "ERROR: client folder does not exist."
            exit 1
          }
          Set-Location "client"

          if (-Not (Test-Path "package-lock.json")) {
            Write-Host "WARNING: package-lock.json is missing - continuing without cache."
          }

          npm install
          npm run build

      # --- SERVER (Node.js) ---
      - name: Ensure Server Lockfile & Install Dependencies
        shell: powershell
        run: |
          if (-Not (Test-Path "server")) {
            Write-Host "ERROR: server folder does not exist."
            exit 1
          }
          Set-Location "server"

          if (-Not (Test-Path "package-lock.json")) {
            Write-Host "WARNING: package-lock.json is missing - continuing without cache."
          }

          npm install

      # --- COPY CLIENT BUILD TO SERVER PUBLIC ---
      - name: Copy React Build into Server Public
        shell: powershell
        run: |
          Set-Location "server"

          if (Test-Path "public") {
            Remove-Item "public" -Recurse -Force
          }

          New-Item -ItemType Directory -Force -Path "public" | Out-Null
          Copy-Item "../client/build/*" "public/" -Recurse -Force

      # --- DEPLOYMENT (PM2) ---
      - name: Stop Existing App (PM2 or Node)
        shell: powershell
        run: |
          pm2 stop all || Write-Host "No running processes to stop."

      - name: Start Node App via PM2
        shell: powershell
        run: |
          Set-Location "server"
          pm2 start server.js --name "my-app"
          pm2 save

      # --- FINAL MESSAGE ---
      - name: Deployment Done
        shell: powershell
        run: |
          Write-Host "✅ Deployment complete on $env:COMPUTERNAME"
