name: Deploy Node + React App (Self-Hosted Windows)

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]  # 👈 Runs directly on your Windows Server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      # --- CLIENT (React App) ---
      - name: Ensure Client Lockfile
        run: |
          if (!(Test-Path ./client/package-lock.json)) {
            echo "ERROR: ./client/package-lock.json is missing. Please run npm install in ./client and commit the lock file."
            exit 1
          }

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci

      - name: Build React App
        working-directory: ./client
        run: npm run build

      # --- SERVER (Node.js) ---
      - name: Ensure Server Lockfile
        run: |
          if (!(Test-Path ./server/package-lock.json)) {
            echo "ERROR: ./server/package-lock.json is missing. Please run npm install in ./server and commit the lock file."
            exit 1
          }

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci

      - name: Copy React Build into Server Public
        run: |
          if (Test-Path .\server\public) { Remove-Item .\server\public -Recurse -Force }
          mkdir .\server\public
          Copy-Item .\client\build\* .\server\public\ -Recurse

      # --- DEPLOYMENT ---
      - name: Stop Existing App (PM2 or Node)
        run: |
          pm2 stop all || echo "No running processes"

      - name: Start Node App via PM2
        working-directory: ./server
        run: |
          pm2 start server.js --name "my-app"
          pm2 save

      # --- FINAL ---
      - name: Deployment Done
        run: |
          echo "✅ Deployment complete on $env:COMPUTERNAME"
